name: GitHub actions simplified

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
  repository_dispatch:
    types: ["**"]

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Run examples
        run: |
          python -m pip install --upgrade pip
          pip install .
          python examples/kem.py
          python examples/sig.py
          python examples/rand.py

      - name: Run unit tests
        run: |
          nose2 --verbose
