name: GitHub actions

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
  repository_dispatch:
    types: ["**"]

permissions:
  contents: read

env:
  BUILD_TYPE: Debug

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nose2

      - name: Run examples POSIX
        if: matrix.os != 'windows-latest'
        run: |
          pip install .
          python examples/kem.py
          echo
          python examples/sig.py
          echo
          python examples/rand.py

      - name: Run unit tests POSIX
        if: matrix.os != 'windows-latest'
        run: |
          nose2 --verbose

      - name: Run examples Windows
        if: matrix.os == 'windows-latest'
        shell: cmd
        run: |
          pip install .
          python examples/kem.py
          echo.
          python examples/sig.py
          echo.
          python examples/rand.py

      - name: Run unit tests Windows
        shell: cmd
        if: matrix.os == 'windows-latest'
        run: |
          nose2 --verbose
